"""AI Clinical Scribe Provider Architecture for Automated Note Generation.

Phase 9.0.8: Automated Clinical Documentation, AI Scribe Synthesis & Structured Note Generation.
Provides:
- Abstract base class BaseClinicalScribeProvider
- Deterministic offline MockClinicalScribeProvider
- Factory function get_scribe_provider()
"""

from abc import ABC, abstractmethod
import logging
from typing import Any, Optional

from app.schemas.note import NoteType

logger = logging.getLogger("medigen.ai.scribe_provider")

SCRIBE_ASSISTIVE_DISCLAIMER = (
    "AI CLINICAL SCRIBE DRAFT: Generated by MediGen AI as assistive clinical decision support. "
    "Must be reviewed, edited, and signed off by the licensed attending physician before clinical reliance. "
    "Does not constitute an autonomous medical diagnosis or prescription."
)


class BaseClinicalScribeProvider(ABC):
    """Abstract interface for multi-modal clinical note synthesis."""

    @abstractmethod
    def synthesize_note(
        self,
        patient_name: str,
        patient_age: Optional[int],
        patient_gender: Optional[str],
        note_type: NoteType,
        encounter_title: Optional[str] = None,
        encounter_assessment: Optional[str] = None,
        encounter_plan: Optional[str] = None,
        medications: Optional[list[str]] = None,
        allergies: Optional[list[str]] = None,
        chat_transcript: Optional[str] = None,
        imaging_findings: Optional[list[str]] = None,
        custom_instructions: Optional[str] = None,
    ) -> tuple[dict[str, Any], str]:
        """Synthesize clinical context into structured JSON sections and rendered text.

        Returns:
            (content_json, raw_text)
        """
        pass


class MockClinicalScribeProvider(BaseClinicalScribeProvider):
    """Deterministic offline clinical scribe provider.

    Generates structured, professional clinical notes across all standard note types
    without requiring external network, LLM APIs, or GPU dependencies.
    """

    def synthesize_note(
        self,
        patient_name: str,
        patient_age: Optional[int],
        patient_gender: Optional[str],
        note_type: NoteType,
        encounter_title: Optional[str] = None,
        encounter_assessment: Optional[str] = None,
        encounter_plan: Optional[str] = None,
        medications: Optional[list[str]] = None,
        allergies: Optional[list[str]] = None,
        chat_transcript: Optional[str] = None,
        imaging_findings: Optional[list[str]] = None,
        custom_instructions: Optional[str] = None,
    ) -> tuple[dict[str, Any], str]:
        logger.info(
            "Synthesizing deterministic clinical note: type=%s",
            note_type.value,
        )

        age_str = f"{patient_age}-year-old" if patient_age else "Adult"
        gender_str = patient_gender or "patient"
        meds_str = ", ".join(medications) if medications else "None reported"
        allergies_str = ", ".join(allergies) if allergies else "No known drug allergies (NKDA)"
        imaging_str = " | ".join(imaging_findings) if imaging_findings else "No diagnostic imaging attached."
        custom_str = f" Focus: {custom_instructions}" if custom_instructions else ""

        if note_type == NoteType.SOAP:
            subjective = (
                f"Patient {patient_name} presents for clinical consultation. "
                f"Reports current medical status with chief concerns noted during clinical encounter."
                f"{custom_str}"
            )
            objective = (
                f"Physical Examination & Diagnostic Summary:\n"
                f"- Demographics: {age_str} {gender_str}\n"
                f"- Active Medications: {meds_str}\n"
                f"- Known Allergies: {allergies_str}\n"
                f"- Diagnostic Imaging Findings: {imaging_str}"
            )
            assessment = (
                encounter_assessment
                or f"Clinical presentation is consistent with documented encounter findings. "
                   f"Differential diagnoses evaluated and active clinical status reviewed."
            )
            plan = (
                encounter_plan
                or f"1. Continue active medication regimen as indicated: {meds_str}.\n"
                   f"2. Schedule routine clinical follow-up in 4 weeks.\n"
                   f"3. Patient advised to seek emergency care for acute symptom exacerbation."
            )
            content_json = {
                "subjective": subjective,
                "objective": objective,
                "assessment": assessment,
                "plan": plan,
            }
            raw_text = (
                f"SOAP CLINICAL NOTE\n\n"
                f"SUBJECTIVE:\n{subjective}\n\n"
                f"OBJECTIVE:\n{objective}\n\n"
                f"ASSESSMENT:\n{assessment}\n\n"
                f"PLAN:\n{plan}\n\n"
                f"---\n{SCRIBE_ASSISTIVE_DISCLAIMER}"
            )

        elif note_type == NoteType.CONSULTATION:
            content_json = {
                "patient": patient_name,
                "reason_for_consultation": encounter_title or "Specialist evaluation and management",
                "clinical_history": f"Patient {patient_name}, {age_str} {gender_str}, referred for clinical evaluation. Meds: {meds_str}.",
                "specialist_assessment": encounter_assessment or "Clinical evaluation demonstrates stable baseline findings.",
                "recommendations": encounter_plan or "Agree with current management plan. Routine follow-up scheduled.",
            }
            raw_text = (
                f"CLINICAL CONSULTATION NOTE — {patient_name}\n\n"
                f"REASON FOR CONSULTATION:\n{content_json['reason_for_consultation']}\n\n"
                f"CLINICAL HISTORY:\n{content_json['clinical_history']}\n\n"
                f"SPECIALIST ASSESSMENT:\n{content_json['specialist_assessment']}\n\n"
                f"RECOMMENDATIONS:\n{content_json['recommendations']}\n\n"
                f"---\n{SCRIBE_ASSISTIVE_DISCLAIMER}"
            )

        elif note_type == NoteType.DISCHARGE_SUMMARY:
            content_json = {
                "patient": patient_name,
                "admission_diagnosis": encounter_title or "Clinical observation and treatment",
                "hospital_course": f"Patient {patient_name}, {age_str} {gender_str}, completed clinical treatment course. Vitals stabilized. Diagnostic imaging: {imaging_str}.",
                "discharge_medications": meds_str,
                "follow_up_instructions": encounter_plan or "Follow up with primary care clinician in 7-14 days. Monitor for warning signs.",
            }
            raw_text = (
                f"DISCHARGE SUMMARY — {patient_name}\n\n"
                f"ADMISSION DIAGNOSIS:\n{content_json['admission_diagnosis']}\n\n"
                f"HOSPITAL COURSE:\n{content_json['hospital_course']}\n\n"
                f"DISCHARGE MEDICATIONS:\n{content_json['discharge_medications']}\n\n"
                f"FOLLOW-UP INSTRUCTIONS:\n{content_json['follow_up_instructions']}\n\n"
                f"---\n{SCRIBE_ASSISTIVE_DISCLAIMER}"
            )

        elif note_type == NoteType.PROCEDURE_NOTE:
            content_json = {
                "patient": patient_name,
                "preoperative_diagnosis": encounter_assessment or "Clinical indication for procedure",
                "postoperative_diagnosis": encounter_assessment or "Clinical procedure completed successfully",
                "procedure_performed": encounter_title or "Standard Diagnostic Procedure",
                "procedure_details": f"Patient {patient_name} prepped and draped in usual sterile fashion. Procedure completed without complications.",
                "findings": imaging_str,
                "post_procedure_plan": encounter_plan or "Routine recovery monitoring. Discharge when criteria met.",
            }
            raw_text = (
                f"PROCEDURE NOTE — {patient_name}\n\n"
                f"PRE-OP DIAGNOSIS: {content_json['preoperative_diagnosis']}\n"
                f"POST-OP DIAGNOSIS: {content_json['postoperative_diagnosis']}\n"
                f"PROCEDURE: {content_json['procedure_performed']}\n\n"
                f"PROCEDURE DETAILS:\n{content_json['procedure_details']}\n\n"
                f"FINDINGS:\n{content_json['findings']}\n\n"
                f"POST-PROCEDURE PLAN:\n{content_json['post_procedure_plan']}\n\n"
                f"---\n{SCRIBE_ASSISTIVE_DISCLAIMER}"
            )

        else:  # REFERRAL_LETTER
            content_json = {
                "patient": patient_name,
                "recipient_specialty": "Specialist Consultation Service",
                "reason_for_referral": encounter_title or "Advanced specialist evaluation",
                "clinical_summary": f"Referring {patient_name} ({age_str} {gender_str}) for further diagnostic and therapeutic evaluation. Current meds: {meds_str}. Known allergies: {allergies_str}.",
                "diagnostic_attachments": imaging_str,
                "requested_actions": encounter_plan or "Please evaluate and advise on specialized management.",
            }
            raw_text = (
                f"CLINICAL REFERRAL LETTER — {patient_name}\n\n"
                f"TO: {content_json['recipient_specialty']}\n\n"
                f"REASON FOR REFERRAL:\n{content_json['reason_for_referral']}\n\n"
                f"CLINICAL SUMMARY:\n{content_json['clinical_summary']}\n\n"
                f"DIAGNOSTIC ATTACHMENTS:\n{content_json['diagnostic_attachments']}\n\n"
                f"REQUESTED ACTIONS:\n{content_json['requested_actions']}\n\n"
                f"---\n{SCRIBE_ASSISTIVE_DISCLAIMER}"
            )

        return content_json, raw_text


def get_scribe_provider() -> BaseClinicalScribeProvider:
    """Factory resolver returning the configured clinical scribe provider."""
    return MockClinicalScribeProvider()
