"""SQLAlchemy models for Clinical AI Agents & Autonomous Care Coordination.

Phase 9.0.17: Advanced Clinical AI Agents & Autonomous Care Coordination.
"""

from datetime import datetime
from typing import TYPE_CHECKING, Any, Optional
from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base

if TYPE_CHECKING:
    from app.models.patient import Patient
    from app.models.user import User


class ClinicalAgentDefinition(Base):
    """Registered specialized clinical AI agent definitions and capability metadata."""

    __tablename__ = "clinical_agent_definitions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    agent_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    agent_type: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[str] = mapped_column(String(32), default="1.0.0", nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    capabilities_json: Mapped[Optional[Any]] = mapped_column(JSON, nullable=True)
    default_action_class: Mapped[str] = mapped_column(String(64), default="RECOMMENDATION", nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class ClinicalAgentRun(Base):
    """Execution lifecycle record for a multi-agent or specialized agent run."""

    __tablename__ = "clinical_agent_runs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    agent_type: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    patient_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("patients.id", ondelete="RESTRICT"), index=True, nullable=False
    )
    initiated_by_user_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    status: Mapped[str] = mapped_column(
        String(32), default="queued", index=True, nullable=False
    )  # queued, running, waiting_for_approval, approved, executed, completed, failed, cancelled
    start_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    end_time: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    input_context_snapshot_json: Mapped[Optional[Any]] = mapped_column(JSON, nullable=True)
    context_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    provenance_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    overall_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    patient: Mapped["Patient"] = relationship("Patient", lazy="select")
    initiated_by_user: Mapped[Optional["User"]] = relationship("User", lazy="select")
    recommendations: Mapped[list["ClinicalAgentRecommendation"]] = relationship(
        "ClinicalAgentRecommendation", back_populates="run", cascade="all, delete-orphan", lazy="select"
    )


class ClinicalAgentRecommendation(Base):
    """Structured, assistive care coordination recommendation generated by an agent."""

    __tablename__ = "clinical_agent_recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    recommendation_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    run_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("clinical_agent_runs.id", ondelete="CASCADE"), index=True, nullable=False
    )
    patient_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("patients.id", ondelete="RESTRICT"), index=True, nullable=False
    )
    category: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    priority: Mapped[str] = mapped_column(String(32), default="medium", index=True, nullable=False)  # urgent, high, medium, low
    action_class: Mapped[str] = mapped_column(
        String(64), default="RECOMMENDATION", index=True, nullable=False
    )  # READ_ONLY, RECOMMENDATION, CLINICIAN_APPROVAL_REQUIRED, HIGH_RISK

    suggested_action_type: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    suggested_action_payload_json: Mapped[Optional[Any]] = mapped_column(JSON, nullable=True)

    approval_status: Mapped[str] = mapped_column(
        String(32), default="pending_review", index=True, nullable=False
    )  # pending_review, approved, rejected, executed, expired
    reviewed_by_user_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    reviewed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    review_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    execution_status: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    executed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    execution_result_json: Mapped[Optional[Any]] = mapped_column(JSON, nullable=True)

    provenance_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    run: Mapped["ClinicalAgentRun"] = relationship("ClinicalAgentRun", back_populates="recommendations", lazy="select")
    patient: Mapped["Patient"] = relationship("Patient", lazy="select")
    reviewed_by_user: Mapped[Optional["User"]] = relationship("User", lazy="select")
    evidence_references: Mapped[list["AgentEvidenceReference"]] = relationship(
        "AgentEvidenceReference", back_populates="recommendation", cascade="all, delete-orphan", lazy="select"
    )


class AgentEvidenceReference(Base):
    """Traceable clinical evidence link supporting a specific agent recommendation."""

    __tablename__ = "agent_evidence_references"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True, autoincrement=True)
    evidence_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    recommendation_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("clinical_agent_recommendations.id", ondelete="CASCADE"), index=True, nullable=False
    )
    entity_type: Mapped[str] = mapped_column(String(64), index=True, nullable=False)  # encounter, observation, alert, care_task, order, result, rpm_observation, quality_gap, trial_match, biomarker
    entity_identifier: Mapped[str] = mapped_column(String(128), nullable=False)
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    excerpt: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float, default=1.0, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    recommendation: Mapped["ClinicalAgentRecommendation"] = relationship(
        "ClinicalAgentRecommendation", back_populates="evidence_references", lazy="select"
    )
