"""Services package for business logic implementations."""

from app.services.doctor_service import (
    activate_doctor,
    create_doctor,
    deactivate_doctor,
    generate_unique_doctor_id,
    get_doctor_by_doctor_id,
    get_doctor_by_id,
    get_doctor_by_registration_number,
    get_doctor_by_user_id,
    list_doctors,
    reject_doctor,
    update_doctor,
    verify_doctor,
)
from app.services.encounter_service import (
    create_encounter,
    generate_unique_encounter_id,
    get_encounter_by_encounter_id,
    get_encounter_by_id,
    list_patient_encounters,
    update_encounter,
)
from app.services.patient_service import (
    create_patient,
    deactivate_patient,
    generate_unique_patient_id,
    get_patient_by_id,
    get_patient_by_patient_id,
    list_patients,
    update_patient,
)
from app.services.user_service import (
    authenticate_user,
    create_user,
    get_user_by_email,
    get_user_by_id,
)

__all__ = [
    "get_user_by_email",
    "get_user_by_id",
    "create_user",
    "authenticate_user",
    "generate_unique_patient_id",
    "get_patient_by_patient_id",
    "get_patient_by_id",
    "create_patient",
    "list_patients",
    "update_patient",
    "deactivate_patient",
    "generate_unique_encounter_id",
    "create_encounter",
    "get_encounter_by_encounter_id",
    "get_encounter_by_id",
    "list_patient_encounters",
    "update_encounter",
    "generate_unique_doctor_id",
    "get_doctor_by_doctor_id",
    "get_doctor_by_user_id",
    "get_doctor_by_registration_number",
    "get_doctor_by_id",
    "create_doctor",
    "list_doctors",
    "update_doctor",
    "verify_doctor",
    "reject_doctor",
    "deactivate_doctor",
    "activate_doctor",
]
